### ISSUE TITLE
JusibyPy versioning

### ISSUE THREAD

**Issue by femisystems** [michaelokuboyejo/jusibe-python-lib#1]
Hi Michael! I tried using this package in a python project but I get this message on installation `Could not find a version that satisfies the requirement jusibe (from versions: )
No matching distribution found for jusibe`. I figured it worked for older versions of python. Would be glad if you could upgrade it to work with python 2.7. Great job by the way

**Comment by michaelokuboyejo** [comment]
Thanks a lot for your feedback, Femi! I would push an update. Thanks again
